feat(run-if-supported)!: update source codes from CommonJS to ESM (#471)
* feat(run-if-supported)!: update source codes from CommonJS to ESM

Currently, [all major Node.js versions support ESM (ECMAScript modules)].
In addition, there are more and more cases where dependent packages [only support pure ESM].
This PR will update CLI source code that does not need to support the old CommonJS to ESM.

BREAKING CHANGE: require Node.js `^12.20.x || >=14.13.1`. This is the [smallest version that supports ESM] and [`node:` imports].

[all major Node.js versions support ESM (ECMAScript modules)]: https://github.com/nodejs/Release/blob/69a3c71fb10a87415e072de77f7d4c65cb52d38e/README.md
[only support pure ESM]: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
[smallest version that supports ESM]: https://nodejs.org/api/esm.html#modules-ecmascript-modules
[`node:` imports]: https://nodejs.org/api/esm.html#node-imports

* fix(run-if-supported): fix syntax error in `src/utils.mts`

    Fixed the following error:

        error TS7060: This syntax is reserved in files with the .mts or .cts extension. Add a trailing comma or explicit constraint.

* fix(run-if-supported): fix type errors caused by `ow` package

* fix(run-if-supported): remove variables and functions that can be used only in CommonJS

    The following variables and functions have been removed:

    + `__filename`
    + `__dirname`
    + `require()`

* build(run-if-supported): allow `import.meta` meta-properties to be used in code

* chore(run-if-supported): allow `node:` imports to be used in code

    `node:` imports have been available since Node.js 12.20.0.
    However, `@types/node@12.20.54` does not include a type definition for `node:` imports.
    Therefore, it has been replaced by `@types/node@14.18.20`.

* build(run-if-supported): fix the `paths` option in `tsconfig.json`

    When ESM mode is enabled, it appears that the file path specified in the [`paths` option] also cannot omit the filename extension.

    [`paths` option]: https://www.typescriptlang.org/tsconfig#paths

* fix(run-if-supported): fix type definition errors

* test(run-if-supported): rewrite test code from .ts to .mts

* style(run-if-supported): format `.mjs` code using dprint

* chore(run-if-supported): use `node:` imports for all import statements

* test(run-if-supported): enable ESM support for Jest and ts-jest

    see
    + https://kulshekhar.github.io/ts-jest/docs/guides/esm-support/
    + https://jestjs.io/docs/ecmascript-modules

* test(run-if-supported): rewrite test code from .mts and .cts to .ts

    ts-jest does not seem to be able to detect `.mjs` and `.cjs`.

* test(run-if-supported): auto-detect `CLI_PATH` from the `bin` field in `package.json` file

* test(run-if-supported): use `@swc/jest` instead of `ts-jest`

    ts-jest fails to convert `.mjs` files in the `src` directory.
    Therefore we replace ts-jest with SWC.

* test(run-if-supported): specify SWC configuration for `@swc/jest`

    By default, `@swc/jest@0.2.21` and `@swc/core@1.2.203` does not seem to detect that `.mts` files are TypeScript.
    This behavior seems to be resolved by setting the compile config.

* revert: test(run-if-supported): rewrite test code from .mts and .cts to .ts

    This reverts commit d2c15c5214350bba5614b222dd91491e6870825a.

* test(run-if-supported): include .mts and .cts in test files found by Jest

* chore(run-if-supported): avoid using `node:` imports in `.cts` files

    Node.js 12 does not support `node:` imports in CommonJS.
    And `.cts` files are converted to CommonJS.
    So we cannot use `node:` imports in `.cts` files.

* chore(deps): update dependency @types/node to v14.18.21

* refactor(run-if-supported): use default import when importing Node.js builtin modules

    When converting to CommonJS with TypeScript, using the default import generated a redundant `__importDefault()` function in converted code.
    To avoid this and reduce package size, until now we have actively used named imports.

    Now we are converting to ESM.
    Using default imports rather than named imports improves both code readability and package size.