fix(ts-utils-is-property-accessible): add "types" import condition into `exports` field in `package.json`
TypeScript 4.7.2 fails to find a type declaration if the `"types"` import condition does not exist.
The following error occurs:

    error TS7016: Could not find a declaration file for module '<package name>'.