fix(ts-utils-is-property-accessible): add "types" import condition into `exports` field in `package.json` (#406)
* fix(ts-utils-is-property-accessible): add "types" import condition into `exports` field in `package.json`

    TypeScript 4.7.2 fails to find a type declaration if the `"types"` import condition does not exist.
    The following error occurs:

        error TS7016: Could not find a declaration file for module '<package name>'.

* chore(ts-utils-is-property-accessible): move "types" import condition to top of exports field

    [The official sample](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#package-json-exports-imports-and-self-referencing) had such code. The intention is unknown, but I think it's better to obey.