chore(deps): update dependency @swc/core to v1.2.208 (#524)
* chore(deps): update dependency @swc/core to v1.2.207

* test(@sounisi5011/run-if-supported): rewrite `tests/helpers/index.cts` to ESM

    On GitHub Actions, the following error was thrown when run on Node.js 14.13.1 or later:

    ```
    SyntaxError: The requested module './helpers/index.cjs' does not provide an export named 'PACKAGE_ROOT'
      at Runtime.linkAndEvaluateModule (../../../node_modules/.pnpm/jest-runtime@28.1.2/node_modules/jest-runtime/build/index.js:828:5)
    ```

    Probably because the boundary between CommonJS and ESM is not working properly.
    So we rewrote `*.cts` to `*.mts`.

* chore(deps): update dependency @swc/core to v1.2.208

* test(jest): use swc's `importInterop` option

    In order to import modules converted to CommonJS from the native ESM of Node.js, `module.importInterop: 'node'` must be specified.
    see https://github.com/swc-project/swc/issues/5084

* revert: test(@sounisi5011/run-if-supported): rewrite `tests/helpers/index.cts` to ESM

    This reverts commit 9af07b383d89eee48004a30ce942db94d8bc1f8c.

* chore(jest): add type definitions to swc config using JsDoc

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Sonishi Izuka <sounisi5011@users.noreply.github.com>