test(@sounisi5011/run-if-supported): rewrite `tests/helpers/index.cts` to ESM
On GitHub Actions, the following error was thrown when run on Node.js 14.13.1 or later:

```
SyntaxError: The requested module './helpers/index.cjs' does not provide an export named 'PACKAGE_ROOT'
  at Runtime.linkAndEvaluateModule (../../../node_modules/.pnpm/jest-runtime@28.1.2/node_modules/jest-runtime/build/index.js:828:5)
```

Probably because the boundary between CommonJS and ESM is not working properly.
So we rewrote `*.cts` to `*.mts`.