chore(deps): update dependency typescript to v4.5.2 (#267)
* chore(deps): update dependency typescript to v4.5.2

* chore(monorepo-workspace-submodules-finder-action): enable the `skipLibCheck` option in `tests` dir

    `jest-mock-process@1.4.1`'s type definition has a problem, causing an error in TypeScript 4.5.

        node_modules/jest-mock-process/dist/index.d.ts:13:154 - error TS2344: Type 'F' does not satisfy the constraint '(...args: any) => any'.
          Type 'T[M]' is not assignable to type '(...args: any) => any'.
            Type 'T[FunctionPropertyNames<T>]' is not assignable to type '(...args: any) => any'.
              Type 'T[T[keyof T] extends (...args: any[]) => any ? keyof T : never]' is not assignable to type '(...args: any) => any'.
                Type 'T[keyof T]' is not assignable to type '(...args: any) => any'.
                  Type 'T[string] | T[number] | T[symbol]' is not assignable to type '(...args: any) => any'.
                    Type 'T[string]' is not assignable to type '(...args: any) => any'.

        node_modules/jest-mock-process/dist/index.d.ts:13:220 - error TS2344: Type 'F' does not satisfy the constraint '(...args: any) => any'.

    To avoid this, enable the `skipLibCheck` option.

Co-authored-by: Renovate Bot <bot@renovateapp.com>
Co-authored-by: Sonishi Izuka <sounisi5011@users.noreply.github.com>