feat(cli)!: update CLI source codes from CommonJS to ESM (#419)
Currently, [all major Node.js versions support ESM (ECMAScript modules)](https://github.com/nodejs/Release/blob/69a3c71fb10a87415e072de77f7d4c65cb52d38e/README.md).
In addition, there are more and more cases where dependent packages [only support pure ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).
This PR will update CLI source code that does not need to support the old CommonJS to ESM.

BREAKING CHANGE: require Node.js `^12.20 || >=14.13`. This is the [smallest version that supports ESM](https://nodejs.org/api/esm.html#modules-ecmascript-modules).

* feat(scripts/globby-exec): update source codes from CommonJS to ESM (ECMAScript modules)

    BREAKING CHANGE: require Node.js `^12.20 || >=14.13`. This is the smallest version that supports ESM.

* fix(scripts/actionlint): switch the module format to ESM and do not use the `.js` extension

* feat(scripts/fix-flatbuffers-generated-ts): update source codes from CommonJS to ESM

    BREAKING CHANGE: require Node.js `^12.20 || >=14.13.1`. This is the smallest version that supports ESM and [`node:` imports](https://nodejs.org/api/esm.html#node-imports).

* feat(scripts/update-package-list): update source codes from CommonJS to ESM

    BREAKING CHANGE: require Node.js `^12.20 || >=14.13.1`. This is the smallest version that supports ESM and [`node:` imports](https://nodejs.org/api/esm.html#node-imports).

* feat(scripts/update-readme-badge): update source codes from CommonJS to ESM

    BREAKING CHANGE: require Node.js `>=14.13.1`. This is the smallest version that supports ESM and [`node:` imports](https://nodejs.org/api/esm.html#node-imports).

* feat(scripts/publish-convert-readme): update source codes from CommonJS to ESM

* feat(scripts/sync-eslintignore-to-dprint-excludes): update source codes from CommonJS to ESM

* refactor(scripts/actionlint): use `import.meta.url` instead of `__dirname`

    `__dirname` can only be used within CommonJS; `import.meta.url` should be used within ESM.

    [#421](https://github.com/sounisi5011/npm-packages/pull/421) change allows `import.meta` property to be used, so replace `__dirname` with `import.meta.url`.

* feat(run-if-supported): update source codes from CommonJS to ESM

    BREAKING CHANGE: require Node.js `^12.20.x || ^14.13.1 || 15.x || 16.x || 17.x`. This is the smallest version that supports ESM and [`node:` imports](https://nodejs.org/api/esm.html#node-imports).

* revert: feat(run-if-supported): update source codes from CommonJS to ESM

    A change in module type caused a large number of errors for which the cause could not be determined:

    + error TS7016: Could not find a declaration file for module 'npm-install-checks'.
    + error TS7016: Could not find a declaration file for module 'parse-json'.
    + error TS2339: Property 'object' does not exist on type 'typeof import(".../node_modules/ow/dist/index")'.

    In particular, the cause of the error that the type definition of the parse-json package cannot be found is unknown. Because @types/parse-json exists as a dependency. In addition, the cross-spawn package has a similar structure, but no error occurs.

    This reverts commit 8e1a66abfcb735113b4dc40b0bf18b7bed485101.