chore(deps): update dependency typescript to v4.7.2 (#394)
* chore(deps): update dependency typescript to v4.7.2

* chore(check-pid-file): disable type errors due to TypeScript bugs

    see https://github.com/microsoft/TypeScript/issues/49235

* chore(monorepo-workspace-submodules-finder-action): add the `--transpile-only` flag to avoid errors

    When using TypeScript 4.7.2 with `@vercel/ncc@0.33.4`, I get the following error:

        Error: Module build failed (from ../../node_modules/.pnpm/@vercel+ncc@0.33.4/node_modules/@vercel/ncc/dist/ncc/loaders/ts-loader.js):
        Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.

    To suppress this error, I added the `--transpile-only` flag to the build command.

Co-authored-by: Renovate Bot <bot@renovateapp.com>
Co-authored-by: Sonishi Izuka <sounisi5011@users.noreply.github.com>